library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

package dsp_pkg is

    -- Tap count = span*rx_sps + 1. The RX filter runs at 2 sps (ddc_fs_4
    -- decimates the 4 sps input by 2), spanning 4 symbols -> 9 taps.
    constant FILTER_LEN : integer := 9;   -- must be odd for symmetry
    subtype coeff_t is signed(15 downto 0);  -- 16-bit signed coefficient

    type coeff_array_t is array(0 to FILTER_LEN - 1) of coeff_t;

    -- Real RRC taps, generated by test_bench/waveform_generator.py
    -- (write_vhdl_coeffs): alpha=0.35, span=4 symbols, peak tap = 2**14.
    --
    -- TX shapes at 4 sps; these are for the RX filter at 2 sps, since
    -- ddc_fs_4 decimates by 2 ahead of it. An RRC is defined in samples per
    -- symbol, so taps generated at the TX rate would stretch the pulse by the
    -- decimation factor and stop being matched.
    --
    -- Regenerate alongside the stimulus - they're only matched if they come
    -- from the same RRC definition. Don't hand edit.
    constant rrc_coeffs : coeff_array_t := (
        to_signed(   854, 16),
        to_signed( -2021, 16),
        to_signed( -1266, 16),
        to_signed(  9089, 16),
        to_signed( 16384, 16),   -- center tap
        to_signed(  9089, 16),
        to_signed( -1266, 16),
        to_signed( -2021, 16),
        to_signed(   854, 16)
    );
    ------------------------------------------------------------------------------
    -- Constants
    ------------------------------------------------------------------------------

    constant DATA_WIDTH    : natural := 16;
    constant PHASE_BITS    : natural := 2;  -- For Fs/4 NCO phase counter
    constant DDC_RATE      : natural := 4;  -- Decimation factor (Fs -> Fs/4)  
    constant COEFF_WIDTH : integer := 16;
    constant OUTPUT_WIDTH : integer := 64;
    constant TRUNCATE_WIDTH : integer := 32;  -- Final desired width

    subtype sample_t is signed(COEFF_WIDTH - 1 downto 0);
    subtype accum_t  is signed(OUTPUT_WIDTH - 1 downto 0);
    subtype out_t    is signed(TRUNCATE_WIDTH - 1 downto 0);

    ------------------------------------------------------------------------------
    -- Type Definitions
    ------------------------------------------------------------------------------
    subtype phase_t        is unsigned(PHASE_BITS - 1 downto 0);

    type iq_sample_t is record
        i : sample_t;
        q : sample_t;
    end record;

    ------------------------------------------------------------------------------
    -- Function/Procedure Declarations (optional)
    ------------------------------------------------------------------------------
    function truncate_and_round(x : signed(63 downto 0); trunc_width: integer; out_width: integer) return out_t;
    -- Function to rotate real sample by Fs/4 phase
    -- Returns an IQ pair
    function fs_by_4_mix(
        x        : sample_t;
        phase    : phase_t
    ) return iq_sample_t;

end package;

package body dsp_pkg is

function truncate_and_round(x : signed(63 downto 0); trunc_width : integer;  out_width: integer) return out_t is
        constant LSB_SHIFT : integer := out_width- trunc_width ;
        variable rounded   : signed(out_width - 1 downto 0) := (others => '0');
        variable result    : signed(trunc_width - 1 downto 0);
    begin
        -- Round-to-nearest by adding half LSB before truncation
        -- Equivalent to: round(x / 2^LSB_SHIFT)
        rounded := x + to_signed(2**(LSB_SHIFT - 1), x'length);

        -- Truncate by taking the top TRUNCATE_WIDTH bits
        result := rounded(out_width - 1 downto LSB_SHIFT);

        return result;
    end function;
  function fs_by_4_mix(
        x        : sample_t;
        phase    : phase_t
    ) return iq_sample_t is
        variable result : iq_sample_t;
    begin
        -- Downconversion is multiplication by exp(-j*w*n) = cos - j*sin, so the
        -- sin term is NEGATED. Using +sin gives the conjugate baseband, which
        -- is a reflected constellation - see the long note in ddc_fs_4.vhd for
        -- why that silently breaks frame sync rather than anything visible.
        case phase is
            when "00" =>  -- cos=1, -sin=0
                result.i := x;
                result.q := (others => '0');
            when "01" =>  -- cos=0, -sin=-1
                result.i := (others => '0');
                result.q := -x;
            when "10" =>  -- cos=-1, -sin=0
                result.i := -x;
                result.q := (others => '0');
            when "11" =>  -- cos=0, -sin=+1
                result.i := (others => '0');
                result.q := x;
            when others =>
                result.i := (others => '0');
                result.q := (others => '0');
        end case;
        return result;
    end function;
    
end package body;