
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

library UNISIM;
use UNISIM.VCOMPONENTS.ALL;

library work;
use work.all;
use work.dsp_pkg.all;
use work.pkg.all;
use work.build_id_pkg.all;

-- Top level for the comms DSP PL design.
--
-- Only the PS7's own dedicated pins (DDR + FIXED_IO) are top-level ports -
-- everything else (AXI-Lite register bus, AXI4-Stream to/from the DMA,
-- clock/reset) is internal between the block design wrapper and the PL
-- logic, so it lives as signals rather than ports.
--
-- Datapath, and TWO clock domains, not one:
--   PS DDR --(AXI DMA MM2S)--> mm2s_* [clk]
--     --(axis_cdc_fifo)--> ADC_IN/data_valid [dsp_clk] --> dsp_top
--     --(axis_cdc_fifo)--> s2mm_* [clk] --(AXI DMA S2MM)--> PS DDR --> Linux --> Ethernet
--
-- dsp_top runs on its own dedicated clock (dsp_clk, FCLK1, 1 MHz) rather
-- than clk (FCLK0, the AXI/DMA side's clock, 40 MHz - a TIMING choice for
-- the matched filter's DSP48 cascade, not a sample-rate one). Before this,
-- data_valid was wired straight to mm2s_tvalid: the DSP chain advanced one
-- sample per AXI-Stream beat, so the "sample rate" was really "however
-- fast DMA happens to deliver bytes", not a chosen number, and
-- mm2s_tready was hardwired '1' (no backpressure at all). The two
-- axis_cdc_fifo.vhd instances below fix both: dsp_top now runs at a real,
-- fs = 1 MHz sample rate (matching every constant already designed against
-- fs = 1 MHz elsewhere - RRC taps, ddc_fs_4's fs/4 carrier placement, both
-- loop_model.py-designed loop filters), decoupled from AXI/DMA throughput,
-- with mm2s_tready now genuinely reflecting whether the FIFO has room.
--
-- reg_rw_interface and sample_sniffer stay on clk (FCLK0) - only the
-- sample-processing chain moves. The sniffer's tap_* inputs cross domains
-- through a plain 2-flop strobe synchronizer (see tap_sync_proc below), not
-- another axis_cdc_fifo - they are diagnostic-only, continuously-driven
-- signals from a MUCH slower source domain (dsp_clk, 1 MHz) sampled by a
-- MUCH faster destination domain (clk, 40 MHz), so a full async FIFO would
-- be needed only if losing an occasional diagnostic sample mattered, which
-- for a monitoring tap it does not.
entity system_top is
  generic (
    -- Where the DSP chain's sample strobe comes from. See valid_src_t in
    -- pkg.vhd. VALID_DMA for a real build; VALID_ALWAYS runs the chain at the
    -- full system clock, which is only meaningful in simulation.
    G_VALID_SRC : valid_src_t := VALID_DMA
  );
  port (
    DDR_0_addr        : inout STD_LOGIC_VECTOR ( 14 downto 0 );
    DDR_0_ba          : inout STD_LOGIC_VECTOR ( 2 downto 0 );
    DDR_0_cas_n       : inout STD_LOGIC;
    DDR_0_ck_n        : inout STD_LOGIC;
    DDR_0_ck_p        : inout STD_LOGIC;
    DDR_0_cke         : inout STD_LOGIC;
    DDR_0_cs_n        : inout STD_LOGIC;
    DDR_0_dm          : inout STD_LOGIC_VECTOR ( 3 downto 0 );
    DDR_0_dq          : inout STD_LOGIC_VECTOR ( 31 downto 0 );
    DDR_0_dqs_n       : inout STD_LOGIC_VECTOR ( 3 downto 0 );
    DDR_0_dqs_p       : inout STD_LOGIC_VECTOR ( 3 downto 0 );
    DDR_0_odt         : inout STD_LOGIC;
    DDR_0_ras_n       : inout STD_LOGIC;
    DDR_0_reset_n     : inout STD_LOGIC;
    DDR_0_we_n        : inout STD_LOGIC;
    FIXED_IO_0_ddr_vrn  : inout STD_LOGIC;
    FIXED_IO_0_ddr_vrp  : inout STD_LOGIC;
    FIXED_IO_0_mio      : inout STD_LOGIC_VECTOR ( 53 downto 0 );
    FIXED_IO_0_ps_clk   : inout STD_LOGIC;
    FIXED_IO_0_ps_porb  : inout STD_LOGIC;
    FIXED_IO_0_ps_srstb : inout STD_LOGIC
  );
end system_top;

architecture Behaviorial of system_top is

signal clk         : std_logic;
signal fclk_resetn : std_logic;                 -- active low, straight from PS7
signal rst         : std_logic;                 -- active high, derived below

-- dsp_top's own dedicated clock domain (FCLK1, 1 MHz - see the entity
-- header comment). Unlike fclk_resetn (PS7-native, direct from FCLK_RESET0_N),
-- fclk1_resetn has no native PS7 pin to tap - PS7 only exposes a dedicated
-- reset for FCLK0. fclk1_resetn is instead generated by a proc_sys_reset_1
-- IP instance in the block design (create_project.tcl), which synchronizes
-- FCLK_RESET0_N into the FCLK_CLK1 domain.
signal dsp_clk         : std_logic;
signal fclk1_resetn    : std_logic;
signal dsp_rst         : std_logic;             -- active high, derived below

-- AXI4-Lite: PS -> reg_rw_interface (user register space).
-- Trimmed to the Lite subset only - the full-AXI4 burst/ID/cache/QoS
-- signals the old version carried (ar/aw burst, cache, id, len, lock, qos,
-- region, size, bid, rid, rlast, wlast) were never used by reg_rw_interface
-- and are dropped. The BD-side master port must be AXI4-Lite to match.
signal s_axi_regs_awaddr  : std_logic_vector(31 downto 0);
signal s_axi_regs_awprot  : std_logic_vector(2 downto 0);
signal s_axi_regs_awvalid : std_logic;
signal s_axi_regs_awready : std_logic;
signal s_axi_regs_wdata   : std_logic_vector(31 downto 0);
signal s_axi_regs_wstrb   : std_logic_vector(3 downto 0);
signal s_axi_regs_wvalid  : std_logic;
signal s_axi_regs_wready  : std_logic;
signal s_axi_regs_bresp   : std_logic_vector(1 downto 0);
signal s_axi_regs_bvalid  : std_logic;
signal s_axi_regs_bready  : std_logic;
signal s_axi_regs_araddr  : std_logic_vector(31 downto 0);
signal s_axi_regs_arprot  : std_logic_vector(2 downto 0);
signal s_axi_regs_arvalid : std_logic;
signal s_axi_regs_arready : std_logic;
signal s_axi_regs_rdata   : std_logic_vector(31 downto 0);
signal s_axi_regs_rresp   : std_logic_vector(1 downto 0);
signal s_axi_regs_rvalid  : std_logic;
signal s_axi_regs_rready  : std_logic;

-- AXI4-Stream, DMA MM2S -> PL (samples out of DDR into the DSP chain).
-- PL is the sink here.
signal mm2s_tdata  : std_logic_vector(31 downto 0);
signal mm2s_tkeep  : std_logic_vector(3 downto 0);
signal mm2s_tlast  : std_logic;
signal mm2s_tvalid : std_logic;
signal mm2s_tready : std_logic;

-- AXI4-Stream, PL -> DMA S2MM (processed samples back into DDR for the PS
-- to pick up and send over Ethernet). PL is the source here.
signal s2mm_tdata  : std_logic_vector(31 downto 0);
signal s2mm_tkeep  : std_logic_vector(3 downto 0);
signal s2mm_tlast  : std_logic;
signal s2mm_tvalid : std_logic;
signal s2mm_tready : std_logic;

-- CDC FIFO: MM2S [clk] -> dsp_top's ADC_IN [dsp_clk]. Just the 16-bit slice
-- dsp_top actually consumes (see the existing TODO on the packing question
-- below) - no need to carry the full 32-bit AXI word across.
constant C_ADC_FIFO_DEPTH : natural := 1024;   -- matches sample_sniffer's
                                                -- C_CAPTURE_DEPTH, plenty to
                                                -- absorb DMA burstiness now
                                                -- that mm2s_tready gives
                                                -- real backpressure
signal fifo_in_wr_full     : std_logic;
signal fifo_in_wr_rst_busy : std_logic;
signal fifo_in_rd_data     : std_logic_vector(15 downto 0);
signal fifo_in_rd_empty    : std_logic;
signal fifo_in_rd_rst_busy : std_logic;

-- CDC FIFO: dsp_top's rx_t* [dsp_clk] -> S2MM [clk]. tdata/tkeep/tlast
-- packed into one word so the frame's framing survives the crossing
-- atomically - unpacked again on the read side.
constant C_RX_FIFO_DEPTH : natural := 16;      -- one frame's worth of 32-bit
                                                -- beats (C_MAX_PAYLOAD_WORDS
                                                -- scale), not a bulk sample
                                                -- stream
signal fifo_out_wr_full     : std_logic;
signal fifo_out_wr_rst_busy : std_logic;
signal fifo_out_wr_data     : std_logic_vector(36 downto 0);   -- tdata & tkeep & tlast
signal dsp_rx_tready        : std_logic;       -- dsp_top's rx_tready, driven
                                                -- by this FIFO now instead
                                                -- of s2mm_tready directly
signal fifo_out_rd_data     : std_logic_vector(36 downto 0);
signal fifo_out_rd_empty    : std_logic;
signal fifo_out_rd_rst_busy : std_logic;

-- dsp_top's own AXI-Stream-style RX output, in [dsp_clk] - separate from
-- s2mm_t* now, which is the FIFO's read side in [clk].
signal dsp_rx_tdata  : std_logic_vector(31 downto 0);
signal dsp_rx_tkeep  : std_logic_vector(3 downto 0);
signal dsp_rx_tlast  : std_logic;
signal dsp_rx_tvalid : std_logic;

signal dsp_valid  : std_logic;    -- sample strobe selected by G_VALID_SRC
signal fpga_reg   : fpgaReg32;    -- PS -> PL, control words
signal status_reg : fpgaStatus32; -- PL -> PS, read-only status/counters
signal tx_start   : std_logic;    -- one-clock pulse from a CONTROL write
signal clr_stats  : std_logic;    -- one-clock pulse from a CONTROL write

-- RX chain status, driven by dsp_top
signal rx_frame_count : unsigned(15 downto 0);
signal rx_err_count   : unsigned(15 downto 0);
signal rx_frame_len   : unsigned(7 downto 0);
signal rx_overflow    : std_logic;
signal rx_in_frame    : std_logic;
signal rx_sync_count  : unsigned(15 downto 0);
signal rx_qual_min    : unsigned(31 downto 0);
signal rx_qual_max    : unsigned(31 downto 0);
signal rx_qual_syms   : unsigned(31 downto 0);

-- Diagnostic sample sniffer (sample_sniffer.vhd) - see the "Diagnostic
-- sample capture" section of pkg.vhd for the address map and register bits
-- this all hangs off. Taps come from dsp_top's tap_* outputs [dsp_clk
-- domain] through tap_sync_proc's synchronizer into tap_*_sync [clk domain
-- - sample_sniffer stays on clk, see the entity header comment]; the
-- capture RAM read port is reached through reg_rw_interface's new
-- capture_rd_* ports rather than a second AXI slave - see the note at the
-- top of reg_rw_interface.vhd for why.
signal tap_ddc_i, tap_ddc_q           : signed(15 downto 0);   -- [dsp_clk]
signal tap_ddc_valid                  : std_logic;             -- [dsp_clk]
signal tap_pll_i, tap_pll_q           : signed(15 downto 0);   -- [dsp_clk]
signal tap_pll_valid                  : std_logic;             -- [dsp_clk]
signal tap_filtered_i, tap_filtered_q : signed(15 downto 0);   -- [dsp_clk]
signal tap_filtered_valid             : std_logic;             -- [dsp_clk]
signal tap_sym_i, tap_sym_q           : signed(15 downto 0);   -- [dsp_clk]
signal tap_sym_valid                  : std_logic;             -- [dsp_clk]

-- Synchronized into [clk] by tap_sync_proc - what sample_sniffer actually
-- reads. Data registers are single-flopped, continuously (not gated) - see
-- the entity header comment for why that is safe here (slow source domain,
-- much faster destination domain sampling it, data held stable for ~40
-- destination cycles between source updates). Only the *_valid strobes get
-- the full 2-flop synchronizer, since those are the signals sample_sniffer
-- actually edge-detects.
signal tap_ddc_i_sync, tap_ddc_q_sync           : signed(15 downto 0);
signal tap_ddc_valid_s1, tap_ddc_valid_sync     : std_logic;
signal tap_pll_i_sync, tap_pll_q_sync           : signed(15 downto 0);
signal tap_pll_valid_s1, tap_pll_valid_sync     : std_logic;
signal tap_filtered_i_sync, tap_filtered_q_sync : signed(15 downto 0);
signal tap_filtered_valid_s1, tap_filtered_valid_sync : std_logic;
signal tap_sym_i_sync, tap_sym_q_sync           : signed(15 downto 0);
signal tap_sym_valid_s1, tap_sym_valid_sync     : std_logic;

signal capture_arm     : std_logic;    -- one-clock pulse from a CONTROL write
signal capture_done    : std_logic;
signal capture_rd_addr : natural range 0 to C_CAPTURE_DEPTH - 1;
signal capture_rd_en   : std_logic;
signal capture_rd_data : std_logic_vector(31 downto 0);

-- Hardware debug (ILA) - round 1: reset behaviour + "does a frame ever
-- complete?" on the dsp_clk domain, see docs/zybo_work.md's hardware-debug
-- section. Round 2 (clk-domain CDC handshake signals: mm2s_t*/s2mm_t*/
-- fifo_*_wr_*) intentionally not marked yet - keeping the first ILA core's
-- probe/BRAM footprint small on a Zybo Z7 until round 1 narrows things down.
-- Vivado's Set Up Debug wizard (post-synthesis, pre-implementation) is where
-- these actually become an ILA core assigned to dsp_clk - this attribute
-- only marks them as candidates and prevents synthesis from optimizing them
-- away.
attribute mark_debug : string;
attribute mark_debug of dsp_rst       : signal is "true";
attribute mark_debug of fclk1_resetn  : signal is "true";
attribute mark_debug of dsp_rx_tvalid : signal is "true";
attribute mark_debug of dsp_rx_tready : signal is "true";
attribute mark_debug of dsp_rx_tlast  : signal is "true";
attribute mark_debug of dsp_valid     : signal is "true";

begin

-- status_reg is what the PS reads back at the RO offsets. Anything the PL
-- doesn't drive is held at zero so reads return something defined rather
-- than 'U'.
status_proc : process (all)
begin
    status_reg <= (others => (others => '0'));

    -- C_REG_ID is not driven here - reg_rw_interface answers that offset from
    -- C_ID_MAGIC directly, and two sources for one register invites drift.

    status_reg(C_REG_STATUS)(C_STAT_FRAME_VALID) <= rx_in_frame;
    status_reg(C_REG_STATUS)(C_STAT_OVERFLOW)    <= rx_overflow;
    -- TODO: TX_BUSY and PLL_LOCKED have no source yet. pll_2nd_order exports
    -- no lock indicator, and there is no TX chain at all.
    status_reg(C_REG_STATUS)(C_STAT_TX_BUSY)     <= '0';
    status_reg(C_REG_STATUS)(C_STAT_PLL_LOCKED)  <= '0';

    status_reg(C_REG_RX_LEN)(7 downto 0)       <= std_logic_vector(rx_frame_len);
    status_reg(C_REG_FRAME_COUNT)(15 downto 0) <= std_logic_vector(rx_frame_count);
    status_reg(C_REG_ERR_COUNT)(15 downto 0)   <= std_logic_vector(rx_err_count);

    status_reg(C_REG_SYNC_COUNT)(15 downto 0)  <= std_logic_vector(rx_sync_count);
    status_reg(C_REG_QUAL_MIN)                 <= std_logic_vector(rx_qual_min);
    status_reg(C_REG_QUAL_MAX)                 <= std_logic_vector(rx_qual_max);
    status_reg(C_REG_QUAL_SYMS)                <= std_logic_vector(rx_qual_syms);

    -- Which git commit this bitstream was built from, and whether the tree was
    -- clean at the time. Constants from the generated build_id_pkg.
    status_reg(C_REG_BUILD_ID)                 <= C_BUILD_ID;
    status_reg(C_REG_STATUS)(C_STAT_BUILD_DIRTY) <= C_BUILD_DIRTY;

    -- Diagnostic sample sniffer: set once a single-shot capture has filled
    -- and frozen, cleared by the next CONTROL.CAPTURE_ARM.
    status_reg(C_REG_STATUS)(C_STAT_CAPTURE_DONE) <= capture_done;
end process;

-- PS7 hands out an active-low reset; dsp_top wants active high, the AXI
-- register block wants active low. Derive both rather than passing one
-- signal into ports of opposite polarity (which the old version did).
rst <= not fclk_resetn;

-- dsp_top's own reset, in its own [dsp_clk] domain. Deliberately its own
-- signal, NOT fclk_resetn - that reset is native to FCLK0/[clk] and is only
-- meta-stability-safe there. dsp_rst is derived from fclk1_resetn, which
-- proc_sys_reset_1 (see create_project.tcl) synchronizes into FCLK_CLK1 for
-- exactly this purpose.
dsp_rst <= not fclk1_resetn;

ps_i : entity work.system_wrapper
  port map (
     DDR_addr             => DDR_0_addr
    ,DDR_ba               => DDR_0_ba
    ,DDR_cas_n            => DDR_0_cas_n
    ,DDR_ck_n             => DDR_0_ck_n
    ,DDR_ck_p             => DDR_0_ck_p
    ,DDR_cke              => DDR_0_cke
    ,DDR_cs_n             => DDR_0_cs_n
    ,DDR_dm               => DDR_0_dm
    ,DDR_dq               => DDR_0_dq
    ,DDR_dqs_n            => DDR_0_dqs_n
    ,DDR_dqs_p            => DDR_0_dqs_p
    ,DDR_odt              => DDR_0_odt
    ,DDR_ras_n            => DDR_0_ras_n
    ,DDR_reset_n          => DDR_0_reset_n
    ,DDR_we_n             => DDR_0_we_n
    ,FIXED_IO_ddr_vrn     => FIXED_IO_0_ddr_vrn
    ,FIXED_IO_ddr_vrp     => FIXED_IO_0_ddr_vrp
    ,FIXED_IO_mio         => FIXED_IO_0_mio
    ,FIXED_IO_ps_clk      => FIXED_IO_0_ps_clk
    ,FIXED_IO_ps_porb     => FIXED_IO_0_ps_porb
    ,FIXED_IO_ps_srstb    => FIXED_IO_0_ps_srstb
    -- AXI4-Lite master out to the user register block
    ,M_AXI_REGS_0_awaddr  => s_axi_regs_awaddr
    ,M_AXI_REGS_0_awprot  => s_axi_regs_awprot
    ,M_AXI_REGS_0_awvalid => s_axi_regs_awvalid
    ,M_AXI_REGS_0_awready => s_axi_regs_awready
    ,M_AXI_REGS_0_wdata   => s_axi_regs_wdata
    ,M_AXI_REGS_0_wstrb   => s_axi_regs_wstrb
    ,M_AXI_REGS_0_wvalid  => s_axi_regs_wvalid
    ,M_AXI_REGS_0_wready  => s_axi_regs_wready
    ,M_AXI_REGS_0_bresp   => s_axi_regs_bresp
    ,M_AXI_REGS_0_bvalid  => s_axi_regs_bvalid
    ,M_AXI_REGS_0_bready  => s_axi_regs_bready
    ,M_AXI_REGS_0_araddr  => s_axi_regs_araddr
    ,M_AXI_REGS_0_arprot  => s_axi_regs_arprot
    ,M_AXI_REGS_0_arvalid => s_axi_regs_arvalid
    ,M_AXI_REGS_0_arready => s_axi_regs_arready
    ,M_AXI_REGS_0_rdata   => s_axi_regs_rdata
    ,M_AXI_REGS_0_rresp   => s_axi_regs_rresp
    ,M_AXI_REGS_0_rvalid  => s_axi_regs_rvalid
    ,M_AXI_REGS_0_rready  => s_axi_regs_rready
    -- DMA MM2S: DDR -> PL
    ,M_AXIS_MM2S_0_tdata  => mm2s_tdata
    ,M_AXIS_MM2S_0_tkeep  => mm2s_tkeep
    ,M_AXIS_MM2S_0_tlast  => mm2s_tlast
    ,M_AXIS_MM2S_0_tvalid => mm2s_tvalid
    ,M_AXIS_MM2S_0_tready => mm2s_tready
    -- DMA S2MM: PL -> DDR
    ,S_AXIS_S2MM_0_tdata  => s2mm_tdata
    ,S_AXIS_S2MM_0_tkeep  => s2mm_tkeep
    ,S_AXIS_S2MM_0_tlast  => s2mm_tlast
    ,S_AXIS_S2MM_0_tvalid => s2mm_tvalid
    ,S_AXIS_S2MM_0_tready => s2mm_tready
    ,fclk                 => clk
    ,fclk_resetn          => fclk_resetn
    ,fclk1                => dsp_clk
    ,fclk1_resetn         => fclk1_resetn
  );

-- MM2S -> dsp_top CDC FIFO. wr_en is qualified by "not full" (never write
-- into a full FIFO, even momentarily); mm2s_tready is driven the same way,
-- independently, so the DMA engine sees real backpressure rather than the
-- old hardwired '1' - this finally closes the backpressure TODO that used
-- to be here. Held low during wr_rst_busy too: the FIFO is not ready to
-- accept writes until its own reset sequencing (spanning both clock
-- domains) completes.
--
-- TODO: 32-bit stream carrying 16-bit I/Q - taking the low half for now to
-- match dsp_top's 16-bit ADC_IN. Decide the packing (interleaved samples vs
-- I in low half / Q in high half) and slice accordingly. Unchanged by this
-- CDC work - still a real open question, just now on the FIFO's write side
-- instead of directly on mm2s_tdata.
mm2s_tready <= (not fifo_in_wr_full) and (not fifo_in_wr_rst_busy);

fifo_in_i : entity work.axis_cdc_fifo
  generic map (
     G_DATA_WIDTH => 16
    ,G_DEPTH      => C_ADC_FIFO_DEPTH
  )
  port map (
     wr_clk      => clk
    ,wr_rst      => rst
    ,wr_en       => mm2s_tvalid and (not fifo_in_wr_full) and (not fifo_in_wr_rst_busy)
    ,wr_data     => mm2s_tdata(15 downto 0)
    ,wr_full     => fifo_in_wr_full
    ,wr_rst_busy => fifo_in_wr_rst_busy

    ,rd_clk      => dsp_clk
    ,rd_rst      => dsp_rst
    ,rd_en       => not fifo_in_rd_empty
    ,rd_data     => fifo_in_rd_data
    ,rd_empty    => fifo_in_rd_empty
    ,rd_rst_busy => fifo_in_rd_rst_busy
  );

-- Sample strobe selection, now against the FIFO's read side rather than
-- mm2s_tvalid directly - dsp_top advances one sample per dsp_clk tick
-- whenever the FIFO has one ready, which at fs = 1 MHz is exactly the real
-- sample rate this chain was designed against (see the entity header
-- comment). VALID_ADC has no source yet - add the port when the ADC path
-- exists.
dsp_valid <= (not fifo_in_rd_empty) when G_VALID_SRC = VALID_DMA else
             '1'                    when G_VALID_SRC = VALID_ALWAYS else
             '0';

uut : entity work.dsp_top
  port map (
     SYS_CLK     => dsp_clk
    ,ARST        => dsp_rst
    ,ADC_IN      => signed(fifo_in_rd_data)
    ,data_valid  => dsp_valid

    ,rx_enable   => fpga_reg(C_REG_CONTROL)(C_CTRL_RX_ENABLE)
    ,clr_stats   => clr_stats

    -- recovered frames -> the CDC FIFO back to clk/S2MM below, not
    -- directly to s2mm_t* any more
    ,rx_tdata    => dsp_rx_tdata
    ,rx_tkeep    => dsp_rx_tkeep
    ,rx_tlast    => dsp_rx_tlast
    ,rx_tvalid   => dsp_rx_tvalid
    ,rx_tready   => dsp_rx_tready

    ,frame_count => rx_frame_count
    ,err_count   => rx_err_count
    ,rx_len      => rx_frame_len
    ,overflow    => rx_overflow
    ,in_frame    => rx_in_frame

    ,sync_count  => rx_sync_count
    ,qual_min    => rx_qual_min
    ,qual_max    => rx_qual_max
    ,qual_syms   => rx_qual_syms

    -- sniffer taps - [dsp_clk], synchronized into [clk] by tap_sync_proc
    -- below before sample_sniffer (which stays on clk) sees them
    ,tap_ddc_i         => tap_ddc_i
    ,tap_ddc_q         => tap_ddc_q
    ,tap_ddc_valid     => tap_ddc_valid
    ,tap_pll_i         => tap_pll_i
    ,tap_pll_q         => tap_pll_q
    ,tap_pll_valid     => tap_pll_valid
    ,tap_filtered_i     => tap_filtered_i
    ,tap_filtered_q     => tap_filtered_q
    ,tap_filtered_valid => tap_filtered_valid
    ,tap_sym_i         => tap_sym_i
    ,tap_sym_q         => tap_sym_q
    ,tap_sym_valid     => tap_sym_valid
  );

-- dsp_top's RX output -> S2MM CDC FIFO. Packs tdata/tkeep/tlast into one
-- word so they cross atomically; rx_frame_buffer's existing valid/ready
-- contract (see rx_frame_buffer.vhd - it already waits on m_tready before
-- advancing) is preserved unchanged, just now against this FIFO instead of
-- directly against s2mm_t*.
fifo_out_wr_data <= dsp_rx_tdata & dsp_rx_tkeep & dsp_rx_tlast;
dsp_rx_tready    <= (not fifo_out_wr_full) and (not fifo_out_wr_rst_busy);

fifo_out_i : entity work.axis_cdc_fifo
  generic map (
     G_DATA_WIDTH => 37
    ,G_DEPTH      => C_RX_FIFO_DEPTH
  )
  port map (
     wr_clk      => dsp_clk
    ,wr_rst      => dsp_rst
    ,wr_en       => dsp_rx_tvalid and (not fifo_out_wr_full) and (not fifo_out_wr_rst_busy)
    ,wr_data     => fifo_out_wr_data
    ,wr_full     => fifo_out_wr_full
    ,wr_rst_busy => fifo_out_wr_rst_busy

    ,rd_clk      => clk
    ,rd_rst      => rst
    ,rd_en       => (not fifo_out_rd_empty) and s2mm_tready
    ,rd_data     => fifo_out_rd_data
    ,rd_empty    => fifo_out_rd_empty
    ,rd_rst_busy => fifo_out_rd_rst_busy
  );

s2mm_tdata  <= fifo_out_rd_data(36 downto 5);
s2mm_tkeep  <= fifo_out_rd_data(4 downto 1);
s2mm_tlast  <= fifo_out_rd_data(0);
s2mm_tvalid <= not fifo_out_rd_empty;

-- Diagnostic sniffer tap synchronizer: dsp_top's tap_* outputs [dsp_clk,
-- 1 MHz] into sample_sniffer's inputs [clk, 40 MHz]. Data registers are
-- single-flopped continuously (not gated by valid) - safe here because the
-- source domain is much slower than the destination sampling it (~40 clk
-- cycles of stable data between each dsp_clk update), so by the time
-- *_valid_sync (the fully-resolved output of the 2-flop strobe
-- synchronizer) asserts, the corresponding data has long since settled -
-- see the entity header comment for the full reasoning. Only *_valid gets
-- the proper 2-flop synchronizer, since that is the signal sample_sniffer
-- actually edge-detects.
tap_sync_proc : process (clk)
begin
    if rising_edge(clk) then
        if rst = '1' then
            tap_ddc_valid_s1 <= '0'; tap_ddc_valid_sync <= '0';
            tap_pll_valid_s1 <= '0'; tap_pll_valid_sync <= '0';
            tap_filtered_valid_s1 <= '0'; tap_filtered_valid_sync <= '0';
            tap_sym_valid_s1 <= '0'; tap_sym_valid_sync <= '0';
        else
            tap_ddc_valid_s1   <= tap_ddc_valid;
            tap_ddc_valid_sync <= tap_ddc_valid_s1;
            tap_ddc_i_sync     <= tap_ddc_i;
            tap_ddc_q_sync     <= tap_ddc_q;

            tap_pll_valid_s1   <= tap_pll_valid;
            tap_pll_valid_sync <= tap_pll_valid_s1;
            tap_pll_i_sync     <= tap_pll_i;
            tap_pll_q_sync     <= tap_pll_q;

            tap_filtered_valid_s1   <= tap_filtered_valid;
            tap_filtered_valid_sync <= tap_filtered_valid_s1;
            tap_filtered_i_sync     <= tap_filtered_i;
            tap_filtered_q_sync     <= tap_filtered_q;

            tap_sym_valid_s1   <= tap_sym_valid;
            tap_sym_valid_sync <= tap_sym_valid_s1;
            tap_sym_i_sync     <= tap_sym_i;
            tap_sym_q_sync     <= tap_sym_q;
        end if;
    end if;
end process;

reg_inst : entity work.reg_rw_interface
  port map (
     clk                     => clk
    ,aresetn                 => fclk_resetn
    ,s_axi_user_regs_awaddr  => s_axi_regs_awaddr
    ,s_axi_user_regs_awprot  => s_axi_regs_awprot
    ,s_axi_user_regs_awvalid => s_axi_regs_awvalid
    ,s_axi_user_regs_awready => s_axi_regs_awready
    ,s_axi_user_regs_wdata   => s_axi_regs_wdata
    ,s_axi_user_regs_wstrb   => s_axi_regs_wstrb
    ,s_axi_user_regs_wvalid  => s_axi_regs_wvalid
    ,s_axi_user_regs_wready  => s_axi_regs_wready
    ,s_axi_user_regs_bresp   => s_axi_regs_bresp
    ,s_axi_user_regs_bvalid  => s_axi_regs_bvalid
    ,s_axi_user_regs_bready  => s_axi_regs_bready
    ,s_axi_user_regs_araddr  => s_axi_regs_araddr
    ,s_axi_user_regs_arprot  => s_axi_regs_arprot
    ,s_axi_user_regs_arvalid => s_axi_regs_arvalid
    ,s_axi_user_regs_arready => s_axi_regs_arready
    ,s_axi_user_regs_rdata   => s_axi_regs_rdata
    ,s_axi_user_regs_rresp   => s_axi_regs_rresp
    ,s_axi_user_regs_rvalid  => s_axi_regs_rvalid
    ,s_axi_user_regs_rready  => s_axi_regs_rready
    ,fpga_reg                => fpga_reg
    ,status_reg              => status_reg
    ,tx_start                => tx_start
    ,clr_stats               => clr_stats
    ,capture_arm             => capture_arm
    ,capture_rd_addr         => capture_rd_addr
    ,capture_rd_en           => capture_rd_en
    ,capture_rd_data         => capture_rd_data
  );

sniffer_inst : entity work.sample_sniffer
  port map (
     clk => clk
    ,rst => rst

    -- Synchronized tap_*_sync signals (tap_sync_proc above), not dsp_top's
    -- raw tap_* outputs directly - those are in [dsp_clk], sample_sniffer
    -- is in [clk].
    ,ddc_i     => tap_ddc_i_sync
    ,ddc_q     => tap_ddc_q_sync
    ,ddc_valid => tap_ddc_valid_sync

    ,pll_i     => tap_pll_i_sync
    ,pll_q     => tap_pll_q_sync
    ,pll_valid => tap_pll_valid_sync

    ,filtered_i     => tap_filtered_i_sync
    ,filtered_q     => tap_filtered_q_sync
    ,filtered_valid => tap_filtered_valid_sync

    ,sym_i     => tap_sym_i_sync
    ,sym_q     => tap_sym_q_sync
    ,sym_valid => tap_sym_valid_sync

    ,tap_sel => fpga_reg(C_REG_MODE)(C_MODE_CAPTURE_TAP_RANGE)

    ,arm  => capture_arm
    ,done => capture_done

    ,rd_addr => capture_rd_addr
    ,rd_en   => capture_rd_en
    ,rd_data => capture_rd_data
  );

end;
