#!/usr/bin/env bash
#
# Generate hdl/build_id.vhd - the git commit baked into the bitstream, so a
# running board can answer "which design is actually loaded?".
#
# create_project.tcl runs the same logic when it builds the project, but this
# exists as a standalone so the file can be produced WITHOUT Vivado: for
# command-line simulation, for CI, and for a fresh clone where system_top.vhd
# would otherwise fail to elaborate on a missing package.
#
# The file is gitignored on purpose. A tracked file rewritten on every build
# would keep the tree permanently dirty, which is exactly the condition
# STATUS.BUILD_DIRTY exists to report.

set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
out="$here/hdl/build_id.vhd"

hash="ffffffff"
dirty=1

if git -C "$here" rev-parse --git-dir >/dev/null 2>&1; then
    hash="$(git -C "$here" rev-parse --short=8 HEAD 2>/dev/null || echo ffffffff)"
    # Any output at all from --porcelain means uncommitted changes.
    if [ -z "$(git -C "$here" status --porcelain 2>/dev/null)" ]; then
        dirty=0
    fi
else
    echo "warning: not a git repository - BUILD_ID = 0xffffffff" >&2
fi

cat > "$out" <<EOF
-- Generated by gen_build_id.sh / create_project.tcl - do not edit, do not commit.
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

package build_id_pkg is
    constant C_BUILD_ID    : std_logic_vector(31 downto 0) := x"${hash}";
    constant C_BUILD_DIRTY : std_logic := '${dirty}';
end package;
EOF

echo "BUILD_ID = 0x${hash} $([ "$dirty" = 1 ] && echo '(DIRTY)' || echo '(clean)')"
echo "wrote $out"
